import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
import tensorflow as tf
import os
import copy
import gc
import sys
import datetime
import argparse

import swpathnet_func

# tensorflowの糞メモリ確保回避のおまじない
config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.allow_growth = True
session = tf.Session(config=config)
keras.backend.set_session(session)


def main(args):
    # 画像サイズの設定
    image_shape = (args.image_size, args.image_size, 3)
    
    # 学習済みモデルの読み込み
    if args.trained_model is None:
        if args.model_name == 'vgg16':
            load_pre_model = keras.applications.vgg16.VGG16
        elif args.model_name == 'xception':
            load_pre_model = keras.applications.xception.Xception
        elif args.model_name == 'inceptionv3':
            load_pre_model = keras.applications.inception_v3.InceptionV3
        elif args.model_name == 'inceptionresnetv2':
            load_pre_model = keras.applications.inception_resnet_v2.InceptionResNetV2
        elif args.model_name == 'densenet':
            load_pre_model = keras.applications.densenet.DenseNet121
        elif args.model_name == 'resnet50':
            load_pre_model = keras.applications.resnet50.ResNet50
        else:
            sys.stderr('invalid model_name: ', args.model_name)
        model = load_pre_model(input_shape=image_shape, 
                                weights=None, 
                                classes=args.num_classes, 
                                include_top=True)
    else:
        model = keras.models.load_model(args.trained_model)

    
    # augumentationの設定
    #   https://github.com/geifmany/cifar-vgg/blob/master/cifar100vgg.pyより拝借
    if args.dont_augment:
        train_datagen = ImageDataGenerator(
                featurewise_center=False,  # set input mean to 0 over the dataset
                samplewise_center=False,  # set each sample mean to 0
                featurewise_std_normalization=False,  # divide inputs by std of the dataset
                samplewise_std_normalization=False,  # divide each input by its std
                zca_whitening=False,  # apply ZCA whitening
                rotation_range=15,  # randomly rotate images in the range (degrees, 0 to 180)
                width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
                height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
                horizontal_flip=True,  # randomly flip images
                vertical_flip=False)  # randomly flip images
    else:
        train_datagen = ImageDataGenerator()
    test_datagen = ImageDataGenerator()
    
    # generatorの設定
    train_generator = train_datagen.flow_from_directory(
        os.path.join(args.dataset_dir, 'train'), 
        target_size=image_shape[:2], 
        batch_size=args.batch_size, 
        class_mode='categorical')
    test_generator = test_datagen.flow_from_directory(
        os.path.join(args.dataset_dir, 'test'), 
        target_size=image_shape[:2], 
        batch_size=args.batch_size, 
        class_mode='categorical')

    # optimizerの指定
    opt = keras.optimizers.Adam()
    
    # gpu並列
    if args.n_gpu != 1:
        with tf.device('/device:CPU:0'):
            tmp_model = pathnet.gene2model(li_geopath[i])
        model = keras.utils.multi_gpu_model(tmp_model, 
                                            gpus=args.n_gpu)
    
    # コンパイル
    model.compile(loss='categorical_crossentropy',
        optimizer=opt,
        metrics=['accuracy'])
    
    # callbacks
    cbks = [keras.callbacks.CSVLogger(os.path.join(args.save_dir, 'scratch_%s_%s.csv' % (args.model_name, args.learning_number)))]
    
    # Fit the model on the batches generated by datagen.flow().
    history = model.fit_generator(
        train_generator,  
        steps_per_epoch=args.num_images_train // args.batch_size, 
        epochs=args.epochs, 
        validation_data=test_generator, 
        validation_steps=args.num_images_test // args.batch_size, 
        use_multiprocessing=args.use_multiprocessing, 
        workers=args.n_thread, 
        callbacks=cbks, 
        verbose=2)
    
    # save history
    df_history = pd.DataFrame(history.history)
    df_history.to_csv(os.path.join(args.save_dir, 'scratch_%s_%s.csv' % (args.model_name, args.learning_number)))

# 引数の読み込み
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    
    # N回回す実験用のアレ
    parser.add_argument('learning_number', help='for sequential experiment')
    
    # データセットのディレクトリ
    parser.add_argument('dataset_dir')
    
    # ログの保存先ディレクトリ
    parser.add_argument('save_dir')
    
    # クラス数
    parser.add_argument('--num_classes', type=int, default=100)
    
    # 学習データの画像数
    #   CIFAR10: 50000, CIFAR100: 50000
    parser.add_argument('--num_images_train', type=int, default=50000, help='CIFAR10: 50000, CIFAR100: 50000')
    
    # テストデータの画像数
    #   CIFAR10: 10000, CIFAR100: 10000
    parser.add_argument('--num_images_test', type=int, default=10000, help='CIFAR10: 10000, CIFAR100: 10000')
    
    # 画像サイズ
    parser.add_argument('--image_size', type=int, default=224)
    
    # バッチサイズ
    parser.add_argument('--batch_size', type=int, default=16)
    
    # エポック
    parser.add_argument('--epochs', type=int, default=60)
    
    # GPU並列
    parser.add_argument('--n_gpu', type=int, default=1)
    
    # CPU並列
    parser.add_argument('--n_thread', type=int, default=1)
    
    # CPU(スレッド)並列
    #   fit_generatorでスレッド並列するとデッドロックする臭い？
    #   https://github.com/keras-team/keras/issues/10340
    parser.add_argument('--use_multiprocessing', action='store_true')
    
    # 水増しの有無
    parser.add_argument('--dont_augment', action='store_false')
    
    # （テスト用）学習済みモデルの設定
    parser.add_argument('--trained_model', default=None)
    
    # 使う学習済みモデル
    parser.add_argument('--model_name',default='vgg16', help='name of pre-trained network. this is disable by giving --trained_model')
    args = parser.parse_args()
    
    print('----PARSED ARGS----\n%s\n-----------------'%args)
    
    main(args)
